# Generated by Django 3.1 on 2020-08-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='_client_borrowed_books_+', to='client.Client'),
        ),
    ]
