# Generated by Django 3.1 on 2020-08-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200821_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='borrowed_books',
        ),
    ]
