# Generated by Django 3.1 on 2020-08-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200821_1807'),
        ('client', '0002_client_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='books',
        ),
        migrations.AddField(
            model_name='client',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, null=True, to='book.Book'),
        ),
    ]
