# Generated by Django 3.1 on 2020-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=9)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('borrow_value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
