# Generated by Django 3.1 on 2020-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_to',
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
