# Generated by Django 3.1 on 2020-08-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200821_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrow_value',
            new_name='borrow_price',
        ),
    ]
